// Code generated by sotvet test fixture. DO NOT EDIT.

package suppressiongenerated

var (
	nolintMissing int //nolint:gosec
	gosecMissing  int // #nosec
	gosecDisable  int //gosec:disable
)

//lint:file-ignore SA1000 generated fixture
func staticcheckFileWide() {}
